[tool.poetry]
name = "modern_python"
version = "0.1.0"
description = "Python template with modern tooling"
authors = ["Chad Hattabaugh <Chad.Hattabaugh@GMail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
